"""empty message

Revision ID: 2d0506f26ba3
Revises: 
Create Date: 2022-01-30 20:32:03.124289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0506f26ba3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('products_name', sa.String(), nullable=True),
    sa.Column('products_quantity', sa.String(), nullable=True),
    sa.Column('product_price', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('main_img', sa.String(), nullable=True),
    sa.Column('img_one', sa.String(), nullable=True),
    sa.Column('img_two', sa.String(), nullable=True),
    sa.Column('describtion_one', sa.String(), nullable=True),
    sa.Column('describtion_two', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('phone_whats_number', sa.String(), nullable=True),
    sa.Column('is_Admin', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('products_name', sa.String(), nullable=True),
    sa.Column('products_quantity', sa.String(), nullable=True),
    sa.Column('product_price', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('main_img', sa.String(), nullable=True),
    sa.Column('products_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['products_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('costumer_name', sa.String(), nullable=True),
    sa.Column('coustmer_email', sa.String(), nullable=True),
    sa.Column('costumer_phone', sa.String(), nullable=True),
    sa.Column('costumer_whats_phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('landmark', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('products_img', sa.String(), nullable=True),
    sa.Column('products_name', sa.String(), nullable=True),
    sa.Column('products_price', sa.String(), nullable=True),
    sa.Column('products_quantity', sa.String(), nullable=True),
    sa.Column('item_total', sa.String(), nullable=True),
    sa.Column('all_total', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('checkout_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checkout_id'], ['checkout.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('checkout')
    op.drop_table('carts')
    op.drop_table('user')
    op.drop_table('products')
    # ### end Alembic commands ###
