"""empty message

Revision ID: 9b036776f1a3
Revises: fcb4a9f92834
Create Date: 2022-01-30 20:56:59.794763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b036776f1a3'
down_revision = 'fcb4a9f92834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_checkout_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'checkout_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('checkout_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_checkout_id_fkey', 'order', 'checkout', ['checkout_id'], ['id'])
    # ### end Alembic commands ###
