"""empty message

Revision ID: bbcb51c5956e
Revises: 2d0506f26ba3
Create Date: 2022-01-30 20:49:03.414532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbcb51c5956e'
down_revision = '2d0506f26ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_checkout_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'checkout_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('checkout_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_checkout_id_fkey', 'order', 'checkout', ['checkout_id'], ['id'])
    # ### end Alembic commands ###
