"""empty message

Revision ID: fcb4a9f92834
Revises: bbcb51c5956e
Create Date: 2022-01-30 20:54:02.485597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb4a9f92834'
down_revision = 'bbcb51c5956e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('checkout_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'checkout', ['checkout_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'checkout_id')
    # ### end Alembic commands ###
